# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b10c8ed8fe42e4374fc256a2537cf25e1e5ae6fb

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token b10c8ed8fe42e4374fc256a2537cf25e1e5ae6fb

{
  "status": "CLOSED",
  "created_at": "2022-07-19T14:54:29.695929Z"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2021-07-21
Content-Type: application/json

###

DELETE {{baseUrl}}/advertisements/1/
Authorization: Token b10c8ed8fe42e4374fc256a2537cf25e1e5ae6fb


###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json